### ISSUE TITLE
Department must be in analytic.account.line view in branch 8.0

### ISSUE THREAD

**Issue by angelmoya** [OCA/department#31]
In this view, department must be show in analytic.account.line:
https://github.com/OCA/department/blob/8.0/analytic_base_department/analytic_view.xml

And would be better if show on analytic analisis to.

I will work on this.

**Comment by angelmoya** [comment]
After check this modules, there are only necesary to add department on analytic analisis, I will work on this

**Comment by dreispt** [comment]
I believe there is nothing more to add here, so I'm closing.
