### ISSUE TITLE
Department in record rules

### ISSUE THREAD

**Issue by angelmoya** [OCA/department#32]
Anyone knows how to use departments in record rules?

Possible solutions:
- Add department field in user, but department information is duplicate.
- Add function field in user to show departments of related users.

Where I could do this? maybe in analytic_base_department, or in new module

**Comment by pedrobaeza** [comment]
I vote for a related field.

**Comment by angelmoya** [comment]
Thanks for the feedback Pedro, in analytic_base_department module? or in new module?

**Comment by pedrobaeza** [comment]
I think analytic_base_department is a good candidate.
