### ISSUE TITLE
Add "App" module for Department Management

### ISSUE THREAD

**Issue by dreispt** [OCA/department#4]
It would add a "Use Departments" checkbox under Configuration -> General Settings, 
This would install a fake module ("activate_department"?) and the feature modules would autoinstall depending on this.

**Comment by bwrsandman** [comment]
Any news on this?

**Comment by dreispt** [comment]
Sorry, won't have time to work on this in the near future.

**Comment by dreispt** [comment]
Breaking up this repo, this feature should go in the `hr` project.
