### ISSUE TITLE
Break up the Department repo

### ISSUE THREAD

**Issue by dreispt** [OCA/department#40]
It now feels unnatural for other repos to add a module here because they want to add the department.
"Department" is not a functional area `per se`.
I get the feeling that adding adding department to a model should be an option in the corresponding repo.

**Comment by pedrobaeza** [comment]
Yeah, I had the same feeling this week, looking for some modules across repositories, so it's a good idea to split these modules in their respectives "main areas" (sale, purchase, account...).

**Comment by dreispt** [comment]
Anyone else agrees / disagrees?

**Comment by dreispt** [comment]
Ping!

**Comment by dreispt** [comment]
I'm starting PRs for this. Let's see how it goes...

**Comment by dreispt** [comment]
No action taken for 8.0.
Discussion opened again for 9.0 at #50.
Closing.
