### ISSUE TITLE
purchase_requisition_department - name conflict

### ISSUE THREAD

**Issue by yvaucher** [OCA/department#43]
A module registered on apps already exists on https://github.com/Vauxoo/addons-vauxoo.git

@zaoral I guess it has exactly the same purpose. Any wish from vauxoo to merge with/use OCA version?

**Comment by dreispt** [comment]
@moylop260 Can you comment on this?

**Comment by moylop260** [comment]
ups
I will work in this case and this other one: https://github.com/OCA/account-analytic/issues/28#issuecomment-91114320
Sorry!

**Comment by yvaucher** [comment]
@moylop260 for https://www.odoo.com/apps/modules/8.0/purchase_requisition_department/ to ensure the right one is on apps, you can simply send a mail to apps@odoo.com to say which one should be seen on apps

Note: if a module is removed from a repository, it's copy will still be available on apps.odoo.com

**Comment by moylop260** [comment]
Hello @yvaucher 
I sent a email to apps@odoo.com with next message:

```
We have next modules in odoo apps from https://github.com/Vauxoo/addons-vauxoo but the stable module is in oca projects:
  - purchase_requisition_department (1)
  - account_analytic_required (2)
  - purchase_discount (3)

Can you redirect this modules of odoo apps to oca modules?

(1) https://github.com/OCA/department/tree/8.0/purchase_requisition_department
(2) https://github.com/OCA/account-analytic/tree/8.0/account_analytic_required
(3) https://github.com/OCA/purchase-workflow/tree/8.0/purchase_discount
```

We will wait reply.

**Comment by yvaucher** [comment]
@moylop260 Thanks

**Comment by moylop260** [comment]
Now is redirect to oca project this modules.
Our apologies by this situation

![uno3](https://cloud.githubusercontent.com/assets/6644187/8256419/9a29eef2-166c-11e5-947f-ffe5fb481b5f.png)

![uno2](https://cloud.githubusercontent.com/assets/6644187/8256420/9a3c8ad0-166c-11e5-93dc-9ab8c11d010b.png)

![uno](https://cloud.githubusercontent.com/assets/6644187/8256421/9a4e5d3c-166c-11e5-8509-8a8a196b8276.png)

**Comment by dreispt** [comment]
Thank you @moylop260

**Comment by yvaucher** [comment]
@moylop260 no worries thanks for having fixed it.
